### ISSUE TITLE
Enable `quotes` rule

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/playcanvas-eslint-config#10]
https://eslint.org/docs/rules/quotes

I propose that we elect either single or double quotes for string literals. Currently, in the engine codebase we have the following occurrences:

* Single quotes: 5464
* Double quotes: 2254

So already, single quotes seemed to be preferred more often by those contributing code. This encourages me to select single quotes as the option we should pick. This is a straightforward auto-fix op.

Thoughts?

**Comment by epreston** [comment]
Single quotes, template literals are useful in shader text replacement.

```
"quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": true }],
```

**Comment by willeastcott** [comment]
@epreston Yep, looks like a reasonable configuration for when we decide to turn this on.

**Comment by epreston** [comment]
The quote props bit is a pure style thing, people might want to drop that.  I like the warning that some property names must be quoted because of specific characters.  It's tempting to see one quoted where it's needed and "fix" it by mistake.

allowTemplateLiterals is super subtle. Sometimes a template literal interface is a clean implementation for heavy text replacement until you need to return an "empty" one.  Then eslint will warn. Then again, you can turn it on in the project settings.
